//
// Created by sams on 3/4/26.
//

#ifndef DEFAULTS_H
#define DEFAULTS_H

#include <stddef.h>

#define CONFIG_DIR "/.local/share/SubOptimal/"

#define HF_BASE_URL "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/"
#define HF_RAW_URL  "https://huggingface.co/ggerganov/whisper.cpp/raw/main/"

#define VAD_MODEL_NAME "ggml-silero-v6.2.0.bin"
#define VAD_MODEL_URL  "https://huggingface.co/ggml-org/whisper-vad/resolve/main/ggml-silero-v6.2.0.bin"

// model weights
#define TRANSLATE_MODEL_URL   "https://huggingface.co/JustFrederik/nllb-200-distilled-600M-ct2/resolve/main/model.bin"
// sentencepiece tokenizer
#define TRANSLATE_SPM_URL     "https://huggingface.co/JustFrederik/nllb-200-distilled-600M-ct2/resolve/main/sentencepiece.bpe.model"
// config
#define TRANSLATE_CONFIG_URL  "https://huggingface.co/JustFrederik/nllb-200-distilled-600M-ct2/resolve/main/config.json"
#define TRANSLATE_MODEL_DIR CONFIG_DIR "nllb-200-distilled-600M-ct2/"

static const char* VALID_MODELS[] = {
    "ggml-tiny.bin",
    "ggml-tiny.en.bin",
    "ggml-base.bin",
    "ggml-base.en.bin",
    "ggml-small.bin",
    "ggml-small.en.bin",
    "ggml-medium.bin",
    "ggml-medium.en.bin",
    "ggml-large-v3.bin",
    "ggml-large-v3-turbo.bin",
    NULL
};

static const char *VALID_LANGUAGES[] = {
    "ace_Arab",
    "ace_Latn",
    "acm_Arab",
    "acq_Arab",
    "aeb_Arab",
    "afr_Latn",
    "ajp_Arab",
    "aka_Latn",
    "amh_Ethi",
    "apc_Arab",
    "arb_Arab",
    "arb_Latn",
    "ars_Arab",
    "ary_Arab",
    "arz_Arab",
    "asm_Beng",
    "ast_Latn",
    "awa_Deva",
    "ayr_Latn",
    "azb_Arab",
    "azj_Latn",
    "bak_Cyrl",
    "bam_Latn",
    "ban_Latn",
    "bel_Cyrl",
    "bem_Latn",
    "ben_Beng",
    "bho_Deva",
    "bjn_Arab",
    "bjn_Latn",
    "bod_Tibt",
    "bos_Latn",
    "bug_Latn",
    "bul_Cyrl",
    "cat_Latn",
    "ceb_Latn",
    "ces_Latn",
    "cjk_Latn",
    "ckb_Arab",
    "crh_Latn",
    "cym_Latn",
    "dan_Latn",
    "deu_Latn",
    "dik_Latn",
    "dyu_Latn",
    "dzo_Tibt",
    "ell_Grek",
    "eng_Latn",
    "epo_Latn",
    "est_Latn",
    "eus_Latn",
    "ewe_Latn",
    "fao_Latn",
    "fij_Latn",
    "fin_Latn",
    "fon_Latn",
    "fra_Latn",
    "fur_Latn",
    "fuv_Latn",
    "gla_Latn",
    "gle_Latn",
    "glg_Latn",
    "grn_Latn",
    "guj_Gujr",
    "hat_Latn",
    "hau_Latn",
    "heb_Hebr",
    "hin_Deva",
    "hne_Deva",
    "hrv_Latn",
    "hun_Latn",
    "hye_Armn",
    "ibo_Latn",
    "ilo_Latn",
    "ind_Latn",
    "isl_Latn",
    "ita_Latn",
    "jav_Latn",
    "jpn_Jpan",
    "kab_Latn",
    "kac_Latn",
    "kam_Latn",
    "kan_Knda",
    "kas_Arab",
    "kas_Deva",
    "kat_Geor",
    "kaz_Cyrl",
    "kbp_Latn",
    "kea_Latn",
    "khm_Khmr",
    "kik_Latn",
    "kin_Latn",
    "kir_Cyrl",
    "kmb_Latn",
    "kmr_Latn",
    "knc_Arab",
    "knc_Latn",
    "kon_Latn",
    "kor_Hang",
    "lao_Laoo",
    "lij_Latn",
    "lim_Latn",
    "lin_Latn",
    "lit_Latn",
    "lmo_Latn",
    "ltg_Latn",
    "ltz_Latn",
    "lua_Latn",
    "lug_Latn",
    "luo_Latn",
    "lus_Latn",
    "lvs_Latn",
    "mag_Deva",
    "mai_Deva",
    "mal_Mlym",
    "mar_Deva",
    "min_Arab",
    "min_Latn",
    "mkd_Cyrl",
    "mlt_Latn",
    "mni_Beng",
    "mos_Latn",
    "mri_Latn",
    "mya_Mymr",
    "nld_Latn",
    "nno_Latn",
    "nob_Latn",
    "npi_Deva",
    "nso_Latn",
    "nus_Latn",
    "nya_Latn",
    "oci_Latn",
    "ory_Orya",
    "pag_Latn",
    "pan_Guru",
    "pap_Latn",
    "pes_Arab",
    "plt_Latn",
    "pol_Latn",
    "por_Latn",
    "prs_Arab",
    "pbt_Arab",
    "quy_Latn",
    "ron_Latn",
    "run_Latn",
    "rus_Cyrl",
    "sag_Latn",
    "san_Deva",
    "sat_Olck",
    "scn_Latn",
    "shn_Mymr",
    "sin_Sinh",
    "slk_Latn",
    "slv_Latn",
    "smo_Latn",
    "sna_Latn",
    "snd_Arab",
    "som_Latn",
    "sot_Latn",
    "spa_Latn",
    "srd_Latn",
    "srp_Cyrl",
    "ssw_Latn",
    "sun_Latn",
    "swe_Latn",
    "swh_Latn",
    "szl_Latn",
    "tam_Taml",
    "taq_Latn",
    "taq_Tfng",
    "tat_Cyrl",
    "tel_Telu",
    "tgk_Cyrl",
    "tgl_Latn",
    "tha_Thai",
    "tir_Ethi",
    "tpi_Latn",
    "tsn_Latn",
    "tso_Latn",
    "tuk_Latn",
    "tum_Latn",
    "tur_Latn",
    "twi_Latn",
    "tzm_Tfng",
    "uig_Arab",
    "ukr_Cyrl",
    "umb_Latn",
    "urd_Arab",
    "uzn_Latn",
    "vec_Latn",
    "vie_Latn",
    "war_Latn",
    "wol_Latn",
    "xho_Latn",
    "ydd_Hebr",
    "yor_Latn",
    "yue_Hant",
    "zho_Hans",
    "zho_Hant",
    "zsm_Latn",
    "zul_Latn",
    NULL
};

static const char *LANGUAGE_NAMES[] = {
    "Acehnese (Arabic script)",
    "Acehnese (Latin script)",
    "Mesopotamian Arabic",
    "Ta'izzi-Adeni Arabic",
    "Tunisian Arabic",
    "Afrikaans",
    "South Levantine Arabic",
    "Akan",
    "Amharic",
    "North Levantine Arabic",
    "Modern Standard Arabic",
    "Modern Standard Arabic (Romanized)",
    "Najdi Arabic",
    "Moroccan Arabic",
    "Egyptian Arabic",
    "Assamese",
    "Asturian",
    "Awadhi",
    "Central Aymara",
    "South Azerbaijani",
    "North Azerbaijani",
    "Bashkir",
    "Bambara",
    "Balinese",
    "Belarusian",
    "Bemba",
    "Bengali",
    "Bhojpuri",
    "Banjar (Arabic script)",
    "Banjar (Latin script)",
    "Standard Tibetan",
    "Bosnian",
    "Buginese",
    "Bulgarian",
    "Catalan",
    "Cebuano",
    "Czech",
    "Chokwe",
    "Central Kurdish",
    "Crimean Tatar",
    "Welsh",
    "Danish",
    "German",
    "Southwestern Dinka",
    "Dyula",
    "Dzongkha",
    "Greek",
    "English",
    "Esperanto",
    "Estonian",
    "Basque",
    "Ewe",
    "Faroese",
    "Fijian",
    "Finnish",
    "Fon",
    "French",
    "Friulian",
    "Nigerian Fulfulde",
    "Scottish Gaelic",
    "Irish",
    "Galician",
    "Guarani",
    "Gujarati",
    "Haitian Creole",
    "Hausa",
    "Hebrew",
    "Hindi",
    "Chhattisgarhi",
    "Croatian",
    "Hungarian",
    "Armenian",
    "Igbo",
    "Ilocano",
    "Indonesian",
    "Icelandic",
    "Italian",
    "Javanese",
    "Japanese",
    "Kabyle",
    "Jingpho",
    "Kamba",
    "Kannada",
    "Kashmiri (Arabic script)",
    "Kashmiri (Devanagari script)",
    "Georgian",
    "Kazakh",
    "Kabiyè",
    "Kabuverdianu",
    "Khmer",
    "Kikuyu",
    "Kinyarwanda",
    "Kyrgyz",
    "Kimbundu",
    "Northern Kurdish",
    "Central Kanuri (Arabic script)",
    "Central Kanuri (Latin script)",
    "Kikongo",
    "Korean",
    "Lao",
    "Ligurian",
    "Limburgish",
    "Lingala",
    "Lithuanian",
    "Lombard",
    "Latgalian",
    "Luxembourgish",
    "Luba-Kasai",
    "Ganda",
    "Luo",
    "Mizo",
    "Standard Latvian",
    "Magahi",
    "Maithili",
    "Malayalam",
    "Marathi",
    "Minangkabau (Arabic script)",
    "Minangkabau (Latin script)",
    "Macedonian",
    "Maltese",
    "Meitei (Bengali script)",
    "Mossi",
    "Maori",
    "Burmese",
    "Dutch",
    "Norwegian Nynorsk",
    "Norwegian Bokmål",
    "Nepali",
    "Northern Sotho",
    "Nuer",
    "Nyanja",
    "Occitan",
    "Odia",
    "Pangasinan",
    "Eastern Panjabi",
    "Papiamento",
    "Western Persian",
    "Plateau Malagasy",
    "Polish",
    "Portuguese",
    "Dari",
    "Southern Pashto",
    "Ayacucho Quechua",
    "Romanian",
    "Rundi",
    "Russian",
    "Sango",
    "Sanskrit",
    "Santali",
    "Sicilian",
    "Shan",
    "Sinhala",
    "Slovak",
    "Slovenian",
    "Samoan",
    "Shona",
    "Sindhi",
    "Somali",
    "Southern Sotho",
    "Spanish",
    "Sardinian",
    "Serbian",
    "Swati",
    "Sundanese",
    "Swedish",
    "Swahili",
    "Silesian",
    "Tamil",
    "Tamasheq (Latin script)",
    "Tamasheq (Tifinagh script)",
    "Tatar",
    "Telugu",
    "Tajik",
    "Tagalog",
    "Thai",
    "Tigrinya",
    "Tok Pisin",
    "Tswana",
    "Tsonga",
    "Turkmen",
    "Tumbuka",
    "Turkish",
    "Twi",
    "Central Atlas Tamazight",
    "Uyghur",
    "Ukrainian",
    "Umbundu",
    "Urdu",
    "Northern Uzbek",
    "Venetian",
    "Vietnamese",
    "Waray",
    "Wolof",
    "Xhosa",
    "Eastern Yiddish",
    "Yoruba",
    "Yue Chinese",
    "Chinese (Simplified)",
    "Chinese (Traditional)",
    "Standard Malay",
    "Zulu",
    NULL
};

#endif //DEFAULTS_H
